version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: dotnet build -c Release ./src/MongoMigrations.sln
workflows:
  version: 2
  build:
    jobs:
      - build