version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: dotnet build -c Release ./src/MongoMigrations.sln
  push:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: dotnet pack src/MongoMigrations/MongoMigrations.csproj -p "$(pwd)/NugetPackages" -c Release
      - run: dotnet push ./NugetPackages/*.nupkg -k $NuGetApiKey
workflows:
  version: 2
  build:
    jobs:
      - build